### ISSUE TITLE
老哥 有什么方法能定位到指定的item吗

### ISSUE THREAD

**Issue by Zhao-Yan-Yan** [pokercc/ExpandableRecyclerView#13]
类似于播放列表  能定位到当前播放的item

**Comment by pokercc** [comment]
具体是什么意思呢？是要使用scrollToPostion()滚动到RecyclerView的指定item吗？

**Comment by Zhao-Yan-Yan** [comment]
![image](https://user-images.githubusercontent.com/39075239/100348366-c7daee80-3021-11eb-905d-bb5c524e41e4.png)

**Comment by Zhao-Yan-Yan** [comment]
差不多 这样应该也行

**Comment by ruibocool** [comment]
notifyDataSetChanged不能生效吗

**Comment by pokercc** [comment]
`notifyDataSetChanged不能生效吗`
请问具体是什么意思呢？

**Comment by pokercc** [comment]
你好，v0.8.0 版本已经修复了`notifyDataSetChanged不能生效`的问题。
