### ISSUE TITLE
老哥，有个关于点击动画的问题您看看是否值得改进一下

### ISSUE THREAD

**Issue by 9292922** [pokercc/ExpandableRecyclerView#22]
问题描述:
在我使用您的库时，设置group项点击展开或关闭子项目的是否开启动画为false时，会导致group项的layout点击的水波纹消失，其实是有的，只是一瞬间，因为水波纹时长也因为我把动画设置为false，即动画显示时长为0而影响了吧，水波纹一闪就过了，只能看到一点点。

因为如果取消了动画，然后group项也没有水波纹的话，下面的子项出现或隐藏会显得很突兀。
主要还是因您所描述的那个bug，所以我就干脆直接关闭动画了。

您看看有没有值得改进一下?

![Video_20210119_093418_470](https://user-images.githubusercontent.com/25112746/105042223-f2d04480-5a9e-11eb-91a7-f4774bfbb01b.gif)
![Video_20210119_093434_186](https://user-images.githubusercontent.com/25112746/105042232-f49a0800-5a9e-11eb-9c59-2c4f0e369734.gif)

**Comment by 9292922** [comment]
我发现就是项目中group覆盖上一个group的下滑动画原因是设置了cardElevation阴影的缘故，设置阴影高度为0dp就行了，但是下滑动画是没问题了，但是项目收起时就算设置了显示动画，还是会直接收起没有任何动画

**Comment by pokercc** [comment]
我复现了第一个问题，关闭展开动画之后，group item 的点击`ripple` 效果，确实有问题，我会抽空改一下。

但是没看懂`cardElevation` 这个是什么问题？

还有是什么原因不能开启展开动画呢？

**Comment by 9292922** [comment]
不是，我是说项目本身不就是有一个bug嘛，就是有时候会出现展开子项时出现覆盖上个子项items的情况（就是你github注明的，同时也写了解决方案），我发现是在设置了阴影的item布局会导致这样，如果吧阴影设置为0同一个布局就不会出现如此情况。



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年1月19日(周二) 晚上10:48
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，有个关于点击动画的问题您看看是否值得改进一下 (#22)




 
我复现了第一个问题，关闭展开动画之后，group item 的点击ripple 效果，确实有问题，我会抽空改一下。
 
但是没看懂cardElevation 这个是什么问题？
 
还有是什么原因不能开启展开动画呢？

**Comment by pokercc** [comment]
`怎么解决child 覆盖group的问题呢？`  是这个吗？我的项目中已经解决了这个问题，我是写出我的解决过程，来阐述为什么裁剪这种方式最高效，可能文字表述让你误会了。

**Comment by pokercc** [comment]
我测试一下item有阴影的问题，这个倒是忽略了。

**Comment by 9292922** [comment]
但是您有看我上面两个GIF嘛？请您看看我在其中两个提问中的GIF，你会发现展开的group items会从它上面的items滑下来展开，依然有动画bug

---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年1月21日(周四) 下午5:52
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，有个关于点击动画的问题您看看是否值得改进一下 (#22)




 
怎么解决child 覆盖group的问题呢？  是这个吗？我的项目中已经解决了这个问题，我是写出我的解决过程，来阐述为什么裁剪这种方式最高效，可能文字表述让你误会了。

**Comment by pokercc** [comment]
收到，我测试一下有阴影的情况。

**Comment by pokercc** [comment]
我在`fix/childItemWithElevation`分支尝试解决item 有z值的问题，但是效果不是很好。
>当子itemView 设置了z或者elevation,在执行动画的过程中将不会显示阴影（Android 9.0 除外)

这是因为View 设置z值，之后，canvas 会对View的renderNode进行重排序，我设置了`Canvas.disableZ()`之后，可以正确裁剪了，但是不能显示阴影了。 

我还在想办法解决中。

https://user-images.githubusercontent.com/17515825/105633107-a8313c80-5e91-11eb-8276-5170f39ee259.mp4

**Comment by 9292922** [comment]
谢谢老哥，那么晚了，早点休息吧！这些急不来，一个好的库总需要慢慢迭代的，目前应该应该就我才发现这个问题，所以不用太急，等以后使用者多了，可能这个就成一个小问题啦



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年1月24日(周日) 晚上10:16
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，有个关于点击动画的问题您看看是否值得改进一下 (#22)




 
我在fix/childItemWithElevation分支尝试解决item 有z值的问题，但是效果不是很好。
  
当子itemView 设置了z或者elevation,在执行动画的过程中将不会显示阴影（Android 9.0 除外)
  
这是因为View 设置z值，之后，canvas 会对View的renderNode进行重排序，我设置了Canvas.disableZ()之后，可以正确裁剪了，但是不能显示阴影了。
 
我还在想办法解决中。
 
https://user-images.githubusercontent.com/17515825/105633107-a8313c80-5e91-11eb-8276-5170f39ee259.mp4

**Comment by pokercc** [comment]
你好，我在最新的`v0.8.5`版本已经修复了View设置`elevation`导致动画异常的问题，请更新一下。

**Comment by pokercc** [comment]
有新的反馈，请再开启，我先关闭了。
