### ISSUE TITLE
关于一个展开子项时比较严重的缺陷

### ISSUE THREAD

**Issue by 9292922** [pokercc/ExpandableRecyclerView#23]
如图，当recyclerview不够空间时，展开子项会直接把上面的项目顶上去，导致上面的项目不可视，能不能设置成不往上顶?如图所示，只在group项下直接展开。
![Video_20210119_102635_913](https://user-images.githubusercontent.com/25112746/105047918-e8fe0f80-5aa5-11eb-88f3-931d6c271398.gif)
![Video_20210119_102725_389](https://user-images.githubusercontent.com/25112746/105047926-ebf90000-5aa5-11eb-9754-78df1d66a542.gif)

**Comment by 9292922** [comment]
可以改进吗?这样非常影响用户体验，或者说我自己有没有可以解决的方案，劳烦您了，我是一个大学生，所以学android不是特别久，所以遇到问题经过研究暂时解决不了只能来请教您，打扰了

**Comment by 9292922** [comment]
我发现你的demo没有这样的问题，就算是长列表也没啥，估计是CoordinatorLayout和CollapsingToolbarLayout结合RercyclerView才出现这样的情况，请问有什么解决方案吗?

**Comment by 9292922** [comment]
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/backgroundColor">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"

        android:layout_height="150dp"
        app:elevation="0dp">


        <com.google.android.material.appbar.SubtitleCollapsingToolbarLayout
            android:id="@+id/CollapsingToolbarLayout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="?attr/backgroundColor"
            app:contentScrim="?attr/backgroundColor"
            app:expandedSubtitleTextAppearance="@style/TextAppearance_subtitle_expanded"
            app:expandedTitleTextAppearance="@style/TextAppearance_title_expanded"
            app:layout_scrollFlags="scroll|exitUntilCollapsed"
            app:subtitle="@string/todo_subtitle"
            app:title="@string/title_todo">

            <ImageView
                android:id="@+id/img_animal_detail"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:contentDescription="@string/d1"
                android:scaleType="centerCrop"
                app:layout_collapseMode="parallax" />

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/tool_bar_detail"
                android:layout_width="match_parent"
                android:layout_height="@dimen/toolbar_height"
                android:theme="@style/Widget.Design.CollapsingToolbar"
                app:layout_collapseMode="pin"
                app:menu="@menu/menu_today"
                app:navigationIcon="@drawable/ic_toolbar_back"
                app:titleTextColor="@color/white" />


        </com.google.android.material.appbar.SubtitleCollapsingToolbarLayout>
        
    </com.google.android.material.appbar.AppBarLayout>


    <androidx.core.widget.NestedScrollView
        android:id="@+id/scrollview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/img_animal_detail"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:id="@+id/empty"
                    android:layout_width="match_parent"
                    android:layout_height="400dp"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent">

                    <ImageView
                        android:id="@+id/ic_empty"
                        android:layout_width="130dp"
                        android:layout_height="130dp"
                        android:contentDescription="@string/d5"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:layout_constraintVertical_bias="0.208"
                        app:srcCompat="@drawable/ic_today_finish" />

                    <TextView
                        android:id="@+id/textView_empty"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="35dp"
                        android:text="@string/you_has_done"
                        android:textColor="?attr/sub_text_Color"
                        android:textSize="16sp"
                        app:layout_constraintEnd_toEndOf="@+id/ic_empty"
                        app:layout_constraintStart_toStartOf="@+id/ic_empty"
                        app:layout_constraintTop_toBottomOf="@+id/ic_empty" />
                </androidx.constraintlayout.widget.ConstraintLayout>

                <pokercc.android.expandablerecyclerview.ExpandableRecyclerView
                    android:id="@+id/recyclerView"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:background="?attr/backgroundColor"
                    android:overScrollMode="never"
                    android:visibility="invisible"
                    app:layout_constraintBottom_toBottomOf="@+id/empty"
                    app:layout_constraintEnd_toEndOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />
            </androidx.constraintlayout.widget.ConstraintLayout>

        </LinearLayout>
    </androidx.core.widget.NestedScrollView>

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_marginEnd="28dp"
        android:layout_marginBottom="28dp"
        android:clickable="true"
        android:focusable="true"
        app:backgroundTint="?attr/colorPrimary"
        app:elevation="4dp"
        app:fabSize="auto"
        app:maxImageSize="20dp"
        app:srcCompat="@drawable/ic_add"
        app:tint="?attr/backgroundColor"
        android:contentDescription="@string/new_todo" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by 9292922** [comment]
我知道了，是我自己连了recyclerview与父布局的上下部才这样的，打扰了

**Comment by pokercc** [comment]
![image](https://user-images.githubusercontent.com/17515825/105048761-ddf7af00-5aa6-11eb-813f-a97b77c9b8b4.png)
- ExpandRecyclerView的layout_height 需要设置match_parent 或者是固定尺寸，不能是wrap_content。
- 另外RecyclerView 外边不能嵌套ScrollView,会导致RecyclerView变成LinearLayout,性能很差，还会产生滑动冲突,可以试试把NestedScrollView换成FrameLayout

**Comment by 9292922** [comment]
谢谢，已经解决了，很感谢您的解答，是我自己在调试各种方法的时候把recyclerview的顶部底部都与父布局关联才这样的。



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年1月19日(周二) 晚上10:44
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 关于一个展开子项时比较严重的缺陷 (#23)




 

  
ExpandRecyclerView的layout_height 需要设置match_parent 或者是固定尺寸，不能是wrap_content。 

另外RecyclerView 外边不能嵌套ScrollView,会导致RecyclerView变成LinearLayout,性能很差，还会产生滑动冲突,可以试试把NestedScrollView换成FrameLayout
