### ISSUE TITLE
上下拉刷新，上拉加载 adapter.notifyDataSetChanged() 数据不会刷新

### ISSUE THREAD

**Issue by minorlai** [pokercc/ExpandableRecyclerView#24]
流程：
服务器返回data(处理后)，adapter.setData()
adapter.expandAllGroup()；
adapter.notifyDataSetChanged();

头部和列表数据均不会刷新，滑动列表替换头部（滑动到第二组）才会更新。

**Comment by pokercc** [comment]
请问使用的版本是？

**Comment by minorlai** [comment]
你好，我是刚更新的最新版本

**Comment by pokercc** [comment]
经过我测试，调用`ExpandableAdapter.notifyDataSetChanged()`,是可以刷新数据的。
```kotlin
   onCreated(){
    // 按钮点击事件
     binding.notifyDataSet.setOnClickListener {
            (binding.recyclerView.adapter as? CountAdapter)?.setNewData()
      }
   }
  
   // 更新adapter数据
   fun setNewData() {
        groupCount = Random.nextInt(1, 10)
        childCount = Random.nextInt(2, 10)
        notifyDataSetChanged()
    }
```
https://user-images.githubusercontent.com/17515825/105851812-874a2200-601e-11eb-92cf-7de116c03446.mp4

**Comment by pokercc** [comment]
可能是我没考虑到的原因导致，方便提供一下复现的demo吗？

**Comment by minorlai** [comment]
是切换数据源导致的，只有一个数据源的时候是没问题的

**Comment by pokercc** [comment]
兄弟你得提供更多信息帮助我排查问题，不然我复现不了，也不知道怎么解决啊
![051281F8](https://user-images.githubusercontent.com/17515825/106082030-ed38c580-6154-11eb-88f5-8b462dea9b11.jpeg)

**Comment by minorlai** [comment]
好的，我稍后提供一个视频

**Comment by pokercc** [comment]
有新的反馈，请再开启，我先关闭了。

**Comment by minorlai** [comment]
大佬，问题复现了，你qq多少？我加下你，发个视频给你看看






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 上午8:55
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;; 
抄送: "Allen"<1150142387@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pokercc/ExpandableRecyclerView] 上下拉刷新，上拉加载 adapter.notifyDataSetChanged() 数据不会刷新 (#24)





 
有新的反馈，请再开启，我先关闭了。

**Comment by pokercc** [comment]
好的，729368896
