### ISSUE TITLE
老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现

### ISSUE THREAD

**Issue by 9292922** [pokercc/ExpandableRecyclerView#28]
问题描述:
当recyclerview设置为warp_content(这个肯定很多时候需要这样做的)
然后，当所有的groupitem全部关闭时，即recyclerview高度是最小的。

然后如下展开其中的groupitem，再闭合。
会发现动画显示不完全！就算不开延迟也明显肉眼可以感受到。

原因分析:
当groupitem展开时，recyclerview高度足够大，然后点击任意groupitem使其闭合，这时，recyclerview就直接刷新高度了(直接刷新为当正在执行groupitem已经关闭的高度)，但是groupitem的sub_Items还在一一往上缩，但是当groupitem被点击时recyclerview已然早就缩到已经关闭的高度了，自然就会导致全部子item往上缩的时候全部都没被显示出来。

下面请看动画放慢的gif，可能比较大，我为了您看得清晰采用了比较高的清晰度，大概8MB

此外，提前祝您旧历新年快乐，新的一年事事顺利，身体健康，事业有成！

![Video_20210209_102117_674](https://user-images.githubusercontent.com/25112746/107307485-ba31f280-6ac1-11eb-8923-4a79d61efa02.gif)

**Comment by pokercc** [comment]
新年快乐，哈哈哈！

**Comment by pokercc** [comment]
设置成wrap_content 高度会发生变化，会导致动画出现问题，这点我在README中也写了。
为什么要把ExpandableRecyclerView高度 设置为wrap_content呢？是想做哪儿种UI效果呢？应该是可以有变通的方式来实现。

**Comment by 9292922** [comment]
一些待做todo列表，用了coordinationlayout，应该是默认全要展开的，而不是让recyclerview盛满屏幕，然后靠滑动来加载更多内容



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 中午1:37
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现 (#28)




 
设置成wrap_content 高度会发生变化，会导致动画出现问题，这点我在README中也写了。
 为什么要把ExpandableRecyclerView高度 设置为wrap_content呢？是想做哪儿种UI效果呢？应该是可以有变通的方式来实现。

**Comment by 9292922** [comment]
我也试过动态设置recyclerview的高度但是总是不得劲，此外还有设置recyclerview的minheight
，这个方法凑效，只是不太好，毕竟当用户的待做列表特别长时总会有超出minheight的时候，而且当列表很短时，recyclerview有额外的高度看起来很奇怪

---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 中午1:37
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现 (#28)




 
设置成wrap_content 高度会发生变化，会导致动画出现问题，这点我在README中也写了。
 为什么要把ExpandableRecyclerView高度 设置为wrap_content呢？是想做哪儿种UI效果呢？应该是可以有变通的方式来实现。

**Comment by 9292922** [comment]
实在很难解决wrap content的话，如果可以解决之前那个展开/隐藏groupitem时布局点击水波阴影动画时长为0的问题，把隐藏/显示时动画关闭，也未尝不是wrap_content的recyclerview较好的视觉效果选择了。



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 中午1:37
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现 (#28)




 
设置成wrap_content 高度会发生变化，会导致动画出现问题，这点我在README中也写了。
 为什么要把ExpandableRecyclerView高度 设置为wrap_content呢？是想做哪儿种UI效果呢？应该是可以有变通的方式来实现。

**Comment by 9292922** [comment]
毕竟有时候确确实实需要把recyclerview设置为wrap_content，无可避免会遇到这个问题。



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年2月9日(周二) 中午1:37
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现 (#28)




 
设置成wrap_content 高度会发生变化，会导致动画出现问题，这点我在README中也写了。
 为什么要把ExpandableRecyclerView高度 设置为wrap_content呢？是想做哪儿种UI效果呢？应该是可以有变通的方式来实现。

**Comment by pokercc** [comment]
抱歉哈，我还没有理解为什么上拉加载更多，需要把RecyclerView 设置成wrap_content，你能把场景说清楚吗？
还有我不好支持RecyclerView 设置wrap_content属性是因为item的展开和收齐确实会导致高度变化，而安卓是不能在执行动画的过程中改变View的高度的，否则会导致缓存失效引起掉帧动画卡顿。

**Comment by 9292922** [comment]
就是在一些界面中，需要用scrollview一次性显示全部items呀，集合coordinationlayout。


对，我也觉得可能这个比较难适配wrap_content，但是其实把之前我提的那个:
当点击隐藏groupitem子项的时候（关闭动画），连点击groupitems的水波纹动画duration也为0了，导致没有点击水波纹效果，这样很奇怪，如果修复了这个，其实不适配warp_content也没关系了，因为收起子项的时候关闭动画就好了



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年2月12日(周五) 上午9:38
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现 (#28)




 
抱歉哈，我还没有理解为什么上拉加载更多，需要把RecyclerView 设置成wrap_content，你能把场景说清楚吗？
 还有我不好支持RecyclerView 设置wrap_content属性是因为item的展开和收齐确实会导致高度变化，而安卓是不能在执行动画的过程中改变View的高度的，否则会导致缓存失效引起掉帧动画卡顿。

**Comment by pokercc** [comment]
使用ScrollView 嵌套RecyclerView 似乎并不是一个很好的方式，会有性能问题和滑动冲突的问题。

关闭动画，水波纹效果不明显的问题，可以这么解决：
1. 设置ExpandableAdapter.enableAnimation  = true
2. 设置ExpandableItemAnimator.animDuration = 0L

**Comment by 9292922** [comment]
好的，谢谢，迟点我试试！



---原始邮件---
发件人: "pokercc"<notifications@github.com&gt;
发送时间: 2021年2月12日(周五) 上午10:23
收件人: "pokercc/ExpandableRecyclerView"<ExpandableRecyclerView@noreply.github.com&gt;;
抄送: "9292922"<2314815201@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [pokercc/ExpandableRecyclerView] 老哥，我又来了，发现了个终极的问题，可能是之前我提的问题的准确复现 (#28)




 
使用ScrollView 嵌套RecyclerView 似乎并不是一个很好的方式，会有性能问题和滑动冲突的问题。
 
关闭动画，水波纹效果不明显的问题，可以这么解决：
  
设置ExpandableAdapter.enableAnimation  = true 

设置ExpandableItemAnimator.animDuration = 0L

**Comment by pokercc** [comment]
我先关闭了，有问题，请再提issue.
