### ISSUE TITLE
如何默认全部展开，并且禁止折叠

### ISSUE THREAD

**Issue by daiwj** [pokercc/ExpandableRecyclerView#29]
1.onBindGroupViewHolder 复写掉 groupViewHolder.itemView 的 click 事件 可以自定义自己的 头部点击事件，是不是只能这么做
2.如何实现默认全部展开

**Comment by pokercc** [comment]
1. 如何禁用折叠，是的，就是复写onBindGroupViewHolder
2. 实现默认全部展开，调用ExpandableAdapter#expandAllGroup()

**Comment by daiwj** [comment]
顺便问下，StickyHeader + GridLayoutManager 可行吗？是不是只要保证 Header 是 独占一行就行？

**Comment by daiwj** [comment]
从demo 看，首次加载的数据是 一个 groupList，有没有办法 实现 groupList 和 childList 一起丢进Adapter？这样是不是不好识别
groupType？

**Comment by pokercc** [comment]
> 顺便问下，StickyHeader + GridLayoutManager 可行吗？是不是只要保证 Header 是 独占一行就行？

应该是可以的，不过需要测试一下

**Comment by pokercc** [comment]
> 从demo 看，首次加载的数据是 一个 groupList，有没有办法 实现 groupList 和 childList 一起丢进Adapter？这样是不是不好识别
> groupType？

ExpandAdapter 我借鉴了安卓系统的ExpandListView的ExpandableListAdapter 的api，继承并实现这两个函数就可以了
```kotlin
    abstract fun getGroupCount(): Int

    abstract fun getChildCount(groupPosition: Int): Int
```
跟传入adapter的数据结构是没有关系的,但是比较推荐使用Tree 类型的数据结构，比较清晰。

**Comment by daiwj** [comment]
> > 从demo 看，首次加载的数据是 一个 groupList，有没有办法 实现 groupList 和 childList 一起丢进Adapter？这样是不是不好识别
> > groupType？
> 
> ExpandAdapter 我借鉴了安卓系统的ExpandListView的ExpandableListAdapter 的api，继承并实现这两个函数就可以了
> 
> ```kotlin
>     abstract fun getGroupCount(): Int
> 
>     abstract fun getChildCount(groupPosition: Int): Int
> ```
> 
> 跟传入adapter的数据结构是没有关系的,但是比较推荐使用Tree 类型的数据结构，比较清晰。

从你代码看，需要expandGroup才会执行onCraeteChildViewHolder和onBind，我是想 把groupList 和 childList 合并成 一个 list 直接丢给adapter，而不是调用 expandAllGroup方式来展开，不知道可不可行，正在尝试。

**Comment by pokercc** [comment]
禁用折叠的话，直接用RecyclerView就可以,还用这个折叠列表干嘛？ 
![image](https://user-images.githubusercontent.com/17515825/108977347-69c2b380-76c3-11eb-99e6-a3b97e54605b.png)

**Comment by daiwj** [comment]
> 禁用折叠的话，直接用RecyclerView就可以,还用这个折叠列表干嘛？
> ![image](https://user-images.githubusercontent.com/17515825/108977347-69c2b380-76c3-11eb-99e6-a3b97e54605b.png)



> > > 从demo 看，首次加载的数据是 一个 groupList，有没有办法 实现 groupList 和 childList 一起丢进Adapter？这样是不是不好识别
> > > groupType？
> > 
> > 
> > ExpandAdapter 我借鉴了安卓系统的ExpandListView的ExpandableListAdapter 的api，继承并实现这两个函数就可以了
> > ```kotlin
> >     abstract fun getGroupCount(): Int
> > 
> >     abstract fun getChildCount(groupPosition: Int): Int
> > ```
> > 
> > 
> > 跟传入adapter的数据结构是没有关系的,但是比较推荐使用Tree 类型的数据结构，比较清晰。
> 
> 从你代码看，需要expandGroup才会执行onCraeteChildViewHolder和onBind，我是想 把groupList 和 childList 合并成 一个 list 直接丢给adapter，而不是调用 expandAllGroup方式来展开，不知道可不可行，正在尝试。

先回答这个问题，尝试后，发现并不行...

**Comment by daiwj** [comment]
> 禁用折叠的话，直接用RecyclerView就可以,还用这个折叠列表干嘛？
> ![image](https://user-images.githubusercontent.com/17515825/108977347-69c2b380-76c3-11eb-99e6-a3b97e54605b.png)

主要看上了你的 StickyHeader 然后，万一以后需要折叠呢

**Comment by pokercc** [comment]
> > > 从demo 看，首次加载的数据是 一个 groupList，有没有办法 实现 groupList 和 childList 一起丢进Adapter？这样是不是不好识别
> > > groupType？
> > 
> > 
> > ExpandAdapter 我借鉴了安卓系统的ExpandListView的ExpandableListAdapter 的api，继承并实现这两个函数就可以了
> > ```kotlin
> >     abstract fun getGroupCount(): Int
> > 
> >     abstract fun getChildCount(groupPosition: Int): Int
> > ```
> > 
> > 
> > 跟传入adapter的数据结构是没有关系的,但是比较推荐使用Tree 类型的数据结构，比较清晰。
> 
> 从你代码看，需要expandGroup才会执行onCraeteChildViewHolder和onBind，我是想 把groupList 和 childList 合并成 一个 list 直接丢给adapter，而不是调用 expandAllGroup方式来展开，不知道可不可行，正在尝试。

这个你可以发一下代码，我看一下

**Comment by daiwj** [comment]
不调用expandAllGroup，而是一开始就把 Group 和 Child 的数据排列好 丢给 adapter，然后数据错乱了，因为会根据getGroupCount 回调 onCreateGroupViewHolder（第二条数据并不是Group实际上），然后根据position去bind的时候 数据就取的不对了

**Comment by pokercc** [comment]
最好能提供一下代码或者是伪代码，光从你的回复上，我也分析不出来。

**Comment by pokercc** [comment]
我先关闭了，有问题，请继续提问。
