### ISSUE TITLE
How to implement the radio selection effect of subitems

### ISSUE THREAD

**Issue by zlybestrong** [pokercc/ExpandableRecyclerView#30]
How to implement the radio selection effect of subitems

**Comment by pokercc** [comment]
Wait a moment, I will offer a sample tomorrow.

**Comment by pokercc** [comment]
I push a sample at [SelectionActivity](https://github.com/pokercc/ExpandableRecyclerView/blob/master/app/src/main/java/pokercc/android/expandablerecyclerview/sample/slection/SelectionActivity.kt)
You can download the sample to found it.
<img src="https://user-images.githubusercontent.com/17515825/110138094-946fe300-7e0c-11eb-8167-577de95559ee.png" width="30%" height="30%"/>
<img src="https://user-images.githubusercontent.com/17515825/110138127-9afe5a80-7e0c-11eb-889f-2a14d11c2f5a.png" width="30%" height="30%"/>
<img src="https://user-images.githubusercontent.com/17515825/110138164-a5205900-7e0c-11eb-918e-6ec737ae99cc.png" width="30%" height="30%"/>
Hope it can help.

**Comment by pokercc** [comment]
I will close this. If you have more questions, please reopen.
