### ISSUE TITLE
Selection option

### ISSUE THREAD

**Issue by mirjalal** [pokercc/ExpandableRecyclerView#6]
Is selection option in your todo list?

**Comment by pokercc** [comment]
Do you mean selection tag in html? I don't find any app use that ui component. Or maybe can you give me a ui design?

**Comment by mirjalal** [comment]
**Single selection example:**
![image](https://user-images.githubusercontent.com/7040450/93659327-06b65c00-fa55-11ea-805a-6213f5d6ee8b.png) | ![image](https://user-images.githubusercontent.com/7040450/93659330-0cac3d00-fa55-11ea-971d-8e8495df961d.png)

**Multiple selection example:**
![image](https://user-images.githubusercontent.com/7040450/93659312-e4244300-fa54-11ea-9344-5c6dd19fe47e.png) | ![image](https://user-images.githubusercontent.com/7040450/93659314-eb4b5100-fa54-11ea-8359-a68b5f8d6ac3.png)

**Comment by pokercc** [comment]
Sorry,I can't figure out  why this widget need expand animation. :sweat_smile:
